"""Migration initiale

Revision ID: cba010a4f00b
Revises: 
Create Date: 2025-08-21 15:19:46.992229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cba010a4f00b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('postnom', sa.String(length=50), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=False),
    sa.Column('adresse', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('dime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membre_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('monnaie', sa.String(length=5), nullable=False),
    sa.Column('numero_recu', sa.String(length=20), nullable=False),
    sa.Column('taux_change', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['membre_id'], ['membre.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_recu')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dime')
    op.drop_table('user')
    op.drop_table('notification')
    op.drop_table('membre')
    # ### end Alembic commands ###
